[package]
name = "kapan"
version = "0.0.1"
edition = "2024_07"
cairo-version = "2.9.4"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.9.4"
# Change to just "openzeppelin" to use full features
openzeppelin = "1.0.0"
alexandria_math = "0.4.0"
ekubo = { git = "https://github.com/EkuboProtocol/abis" }

[dev-dependencies]
openzeppelin_utils = "1.0.0"
snforge_std = "0.49.0"

[[target.starknet-contract]]
casm = true
sierra = true

[tool.fmt]
sort-module-level-items = true

[tool.scarb]  
allow-prebuilt-plugins = ["snforge_std"]
[tool.snforge]
threads = 1

[[tool.snforge.fork]]
name = "MAINNET_LATEST"
url = "https://starknet-mainnet.public.blastapi.io/rpc/v0_8"
block_id.number = "2205419"

[scripts]
test = "snforge test"
