[package]
name = "kapan"
version = "0.0.1"
edition = "2024_07"
cairo-version = "2.11.4"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.11.4"
# Change to just "openzeppelin" to use full features
openzeppelin = "1.0.0"
alexandria_math = "0.4.0"

[dev-dependencies]
openzeppelin_utils = "1.0.0"
snforge_std = "0.41.0"

[[target.starknet-contract]]
casm = true

[tool.fmt]
sort-module-level-items = true

[tool.scarb]  
allow-prebuilt-plugins = ["snforge_std"]

[[tool.snforge.fork]]
name = "MAINNET_LATEST"
url = "https://starknet-mainnet.public.blastapi.io/rpc/v0_8"
block_id.tag = "latest"

[scripts]
test = "snforge test"
