/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */
import { Abi } from "starknet";

export interface SNContract {
  address: string;
  abi: Abi;
  classHash: string;
}

export interface SNContractsType {
  [chainId: string]: {
    [contractName: string]: SNContract;
  };
}

const contracts = {
  devnet: {
    VesuGateway: {
      address:
        "0x3e7906fd7568ce5d203491e579e8764430a6cc632566db38d6802c40657ec32",
      abi: [
        {
          type: "impl",
          name: "IGatewayImpl",
          interface_name: "contracts::interfaces::IGateway::IGateway",
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::interfaces::IGateway::Collateral",
          members: [
            {
              name: "token",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "amount",
              type: "core::integer::u256",
            },
          ],
        },
        {
          type: "struct",
          name: "core::array::Span::<core::felt252>",
          members: [
            {
              name: "snapshot",
              type: "@core::array::Array::<core::felt252>",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::interfaces::IGateway::IGateway",
          items: [
            {
              type: "function",
              name: "deposit",
              inputs: [
                {
                  name: "token",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "user",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "borrow",
              inputs: [
                {
                  name: "token",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "user",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "repay",
              inputs: [
                {
                  name: "token",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "user",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "deposit_collateral",
              inputs: [
                {
                  name: "market",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "collateral",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
                {
                  name: "receiver",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "withdraw_collateral",
              inputs: [
                {
                  name: "market",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "collateral",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "user",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
              ],
              outputs: [
                {
                  type: "(core::starknet::contract_address::ContractAddress, core::integer::u256)",
                },
              ],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_balance",
              inputs: [
                {
                  name: "token",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "user",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_borrow_balance",
              inputs: [
                {
                  name: "token",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "user",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_borrow_balance_current",
              inputs: [
                {
                  name: "token",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "user",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_borrow_rate",
              inputs: [
                {
                  name: "token",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "(core::integer::u256, core::bool)",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_supply_rate",
              inputs: [
                {
                  name: "token",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "(core::integer::u256, core::bool)",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_ltv",
              inputs: [
                {
                  name: "token",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "user",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::integer::u256",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_possible_collaterals",
              inputs: [
                {
                  name: "token",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "user",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "(core::array::Array::<core::starknet::contract_address::ContractAddress>, core::array::Array::<core::integer::u256>, core::array::Array::<core::felt252>, core::array::Array::<core::integer::u8>)",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "is_collateral_supported",
              inputs: [
                {
                  name: "market",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "collateral",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_supported_collaterals",
              inputs: [
                {
                  name: "market",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::array::Array::<core::starknet::contract_address::ContractAddress>",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_encoded_collateral_approvals",
              inputs: [
                {
                  name: "token",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "collaterals",
                  type: "core::array::Array::<contracts::interfaces::IGateway::Collateral>",
                },
              ],
              outputs: [
                {
                  type: "(core::array::Array::<core::starknet::contract_address::ContractAddress>, core::array::Array::<core::array::Span::<core::felt252>>)",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_encoded_debt_approval",
              inputs: [
                {
                  name: "token",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "amount",
                  type: "core::integer::u256",
                },
                {
                  name: "user",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "(core::array::Array::<core::starknet::contract_address::ContractAddress>, core::array::Array::<core::array::Span::<core::felt252>>)",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_inbound_collateral_actions",
              inputs: [
                {
                  name: "token",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "collaterals",
                  type: "core::array::Array::<contracts::interfaces::IGateway::Collateral>",
                },
              ],
              outputs: [
                {
                  type: "(core::array::Array::<core::starknet::contract_address::ContractAddress>, core::array::Array::<core::array::Span::<core::felt252>>)",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "vesu_singleton",
              type: "core::starknet::contract_address::ContractAddress",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::gateways::VesuGateway::VesuGateway::Event",
          kind: "enum",
          variants: [],
        },
      ],
      classHash:
        "0x2d99756f777e97cacdebde9e94480f9b6b935ddd9f7308c5fffce75b21c2800",
    },
  },
} as const satisfies SNContractsType;

export default contracts;
