/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */
import { Abi } from "starknet";

export interface SNContract {
  address: string;
  abi: Abi;
  classHash: string;
}

export interface SNContractsType {
  [chainId: string]: {
    [contractName: string]: SNContract;
  };
}

const contracts = {
  devnet: {
    VesuGateway: {
      address:
        "0x5793c57649dfea4a74fa4ab59c44f36d2d59e16775545d1c895e186200e1ba4",
      abi: [
        {
          type: "impl",
          name: "IVesuGatewayAdminImpl",
          interface_name: "kapan::gateways::VesuGateway::IVesuGatewayAdmin",
        },
        {
          type: "interface",
          name: "kapan::gateways::VesuGateway::IVesuGatewayAdmin",
          items: [
            {
              type: "function",
              name: "add_asset",
              inputs: [
                {
                  name: "asset",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
          ],
        },
        {
          type: "impl",
          name: "ILendingInstructionProcessorImpl",
          interface_name:
            "kapan::interfaces::IGateway::ILendingInstructionProcessor",
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "struct",
          name: "kapan::interfaces::IGateway::BasicInstruction",
          members: [
            {
              name: "token",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "amount",
              type: "core::integer::u256",
            },
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
            },
          ],
        },
        {
          type: "struct",
          name: "core::array::Span::<core::felt252>",
          members: [
            {
              name: "snapshot",
              type: "@core::array::Array::<core::felt252>",
            },
          ],
        },
        {
          type: "enum",
          name: "core::option::Option::<core::array::Span::<core::felt252>>",
          variants: [
            {
              name: "Some",
              type: "core::array::Span::<core::felt252>",
            },
            {
              name: "None",
              type: "()",
            },
          ],
        },
        {
          type: "struct",
          name: "kapan::interfaces::IGateway::Deposit",
          members: [
            {
              name: "basic",
              type: "kapan::interfaces::IGateway::BasicInstruction",
            },
            {
              name: "context",
              type: "core::option::Option::<core::array::Span::<core::felt252>>",
            },
          ],
        },
        {
          type: "struct",
          name: "kapan::interfaces::IGateway::Borrow",
          members: [
            {
              name: "basic",
              type: "kapan::interfaces::IGateway::BasicInstruction",
            },
            {
              name: "context",
              type: "core::option::Option::<core::array::Span::<core::felt252>>",
            },
          ],
        },
        {
          type: "struct",
          name: "kapan::interfaces::IGateway::Repay",
          members: [
            {
              name: "basic",
              type: "kapan::interfaces::IGateway::BasicInstruction",
            },
            {
              name: "context",
              type: "core::option::Option::<core::array::Span::<core::felt252>>",
            },
          ],
        },
        {
          type: "struct",
          name: "kapan::interfaces::IGateway::Withdraw",
          members: [
            {
              name: "basic",
              type: "kapan::interfaces::IGateway::BasicInstruction",
            },
            {
              name: "context",
              type: "core::option::Option::<core::array::Span::<core::felt252>>",
            },
          ],
        },
        {
          type: "enum",
          name: "kapan::interfaces::IGateway::LendingInstruction",
          variants: [
            {
              name: "Deposit",
              type: "kapan::interfaces::IGateway::Deposit",
            },
            {
              name: "Borrow",
              type: "kapan::interfaces::IGateway::Borrow",
            },
            {
              name: "Repay",
              type: "kapan::interfaces::IGateway::Repay",
            },
            {
              name: "Withdraw",
              type: "kapan::interfaces::IGateway::Withdraw",
            },
          ],
        },
        {
          type: "struct",
          name: "core::array::Span::<kapan::interfaces::IGateway::LendingInstruction>",
          members: [
            {
              name: "snapshot",
              type: "@core::array::Array::<kapan::interfaces::IGateway::LendingInstruction>",
            },
          ],
        },
        {
          type: "struct",
          name: "core::array::Span::<(core::starknet::contract_address::ContractAddress, core::felt252, core::array::Array::<core::felt252>)>",
          members: [
            {
              name: "snapshot",
              type: "@core::array::Array::<(core::starknet::contract_address::ContractAddress, core::felt252, core::array::Array::<core::felt252>)>",
            },
          ],
        },
        {
          type: "interface",
          name: "kapan::interfaces::IGateway::ILendingInstructionProcessor",
          items: [
            {
              type: "function",
              name: "process_instructions",
              inputs: [
                {
                  name: "instructions",
                  type: "core::array::Span::<kapan::interfaces::IGateway::LendingInstruction>",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_authorizations_for_instructions",
              inputs: [
                {
                  name: "instructions",
                  type: "core::array::Span::<kapan::interfaces::IGateway::LendingInstruction>",
                },
              ],
              outputs: [
                {
                  type: "core::array::Span::<(core::starknet::contract_address::ContractAddress, core::felt252, core::array::Array::<core::felt252>)>",
                },
              ],
              state_mutability: "external",
            },
          ],
        },
        {
          type: "impl",
          name: "IVesuViewerImpl",
          interface_name: "kapan::gateways::VesuGateway::IVesuViewer",
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "struct",
          name: "kapan::gateways::VesuGateway::PositionWithAmounts",
          members: [
            {
              name: "collateral_shares",
              type: "core::integer::u256",
            },
            {
              name: "collateral_amount",
              type: "core::integer::u256",
            },
            {
              name: "nominal_debt",
              type: "core::integer::u256",
            },
            {
              name: "is_vtoken",
              type: "core::bool",
            },
          ],
        },
        {
          type: "struct",
          name: "kapan::interfaces::vesu_data::AssetPrice",
          members: [
            {
              name: "value",
              type: "core::integer::u256",
            },
            {
              name: "is_valid",
              type: "core::bool",
            },
          ],
        },
        {
          type: "struct",
          name: "kapan::gateways::VesuGateway::TokenMetadata",
          members: [
            {
              name: "address",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "symbol",
              type: "core::felt252",
            },
            {
              name: "decimals",
              type: "core::integer::u8",
            },
            {
              name: "rate_accumulator",
              type: "core::integer::u256",
            },
            {
              name: "utilization",
              type: "core::integer::u256",
            },
            {
              name: "fee_rate",
              type: "core::integer::u256",
            },
            {
              name: "price",
              type: "kapan::interfaces::vesu_data::AssetPrice",
            },
            {
              name: "total_nominal_debt",
              type: "core::integer::u256",
            },
            {
              name: "last_rate_accumulator",
              type: "core::integer::u256",
            },
            {
              name: "reserve",
              type: "core::integer::u256",
            },
            {
              name: "scale",
              type: "core::integer::u256",
            },
          ],
        },
        {
          type: "interface",
          name: "kapan::gateways::VesuGateway::IVesuViewer",
          items: [
            {
              type: "function",
              name: "get_all_positions",
              inputs: [
                {
                  name: "user",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::array::Array::<(core::starknet::contract_address::ContractAddress, core::starknet::contract_address::ContractAddress, kapan::gateways::VesuGateway::PositionWithAmounts)>",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_supported_assets_array",
              inputs: [],
              outputs: [
                {
                  type: "core::array::Array::<core::starknet::contract_address::ContractAddress>",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_supported_assets_ui",
              inputs: [],
              outputs: [
                {
                  type: "core::array::Array::<kapan::gateways::VesuGateway::TokenMetadata>",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "impl",
          name: "OwnableMixinImpl",
          interface_name: "openzeppelin_access::ownable::interface::OwnableABI",
        },
        {
          type: "interface",
          name: "openzeppelin_access::ownable::interface::OwnableABI",
          items: [
            {
              type: "function",
              name: "owner",
              inputs: [],
              outputs: [
                {
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "transfer_ownership",
              inputs: [
                {
                  name: "new_owner",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "renounce_ownership",
              inputs: [],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "transferOwnership",
              inputs: [
                {
                  name: "newOwner",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "renounceOwnership",
              inputs: [],
              outputs: [],
              state_mutability: "external",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "vesu_singleton",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "pool_id",
              type: "core::felt252",
            },
            {
              name: "supported_assets",
              type: "core::array::Array::<core::starknet::contract_address::ContractAddress>",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferred",
          kind: "struct",
          members: [
            {
              name: "previous_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "new_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferStarted",
          kind: "struct",
          members: [
            {
              name: "previous_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "new_owner",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
          ],
        },
        {
          type: "event",
          name: "openzeppelin_access::ownable::ownable::OwnableComponent::Event",
          kind: "enum",
          variants: [
            {
              name: "OwnershipTransferred",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferred",
              kind: "nested",
            },
            {
              name: "OwnershipTransferStarted",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::OwnershipTransferStarted",
              kind: "nested",
            },
          ],
        },
        {
          type: "event",
          name: "kapan::gateways::VesuGateway::VesuGateway::Event",
          kind: "enum",
          variants: [
            {
              name: "OwnableEvent",
              type: "openzeppelin_access::ownable::ownable::OwnableComponent::Event",
              kind: "flat",
            },
          ],
        },
      ],
      classHash:
        "0x5acc7d15a24f6105e48666e09a4046249bf454022aa0187b10cfca3ed682558",
    },
    NostraGateway: {
      address:
        "0x5d3e07258be7763ff5d01754e33204f19c87207473ce1a9a78f56ff59668a4a",
      abi: [
        {
          type: "impl",
          name: "ILendingInstructionProcessorImpl",
          interface_name:
            "kapan::interfaces::IGateway::ILendingInstructionProcessor",
        },
        {
          type: "struct",
          name: "core::integer::u256",
          members: [
            {
              name: "low",
              type: "core::integer::u128",
            },
            {
              name: "high",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "struct",
          name: "kapan::interfaces::IGateway::BasicInstruction",
          members: [
            {
              name: "token",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "amount",
              type: "core::integer::u256",
            },
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
            },
          ],
        },
        {
          type: "struct",
          name: "core::array::Span::<core::felt252>",
          members: [
            {
              name: "snapshot",
              type: "@core::array::Array::<core::felt252>",
            },
          ],
        },
        {
          type: "enum",
          name: "core::option::Option::<core::array::Span::<core::felt252>>",
          variants: [
            {
              name: "Some",
              type: "core::array::Span::<core::felt252>",
            },
            {
              name: "None",
              type: "()",
            },
          ],
        },
        {
          type: "struct",
          name: "kapan::interfaces::IGateway::Deposit",
          members: [
            {
              name: "basic",
              type: "kapan::interfaces::IGateway::BasicInstruction",
            },
            {
              name: "context",
              type: "core::option::Option::<core::array::Span::<core::felt252>>",
            },
          ],
        },
        {
          type: "struct",
          name: "kapan::interfaces::IGateway::Borrow",
          members: [
            {
              name: "basic",
              type: "kapan::interfaces::IGateway::BasicInstruction",
            },
            {
              name: "context",
              type: "core::option::Option::<core::array::Span::<core::felt252>>",
            },
          ],
        },
        {
          type: "struct",
          name: "kapan::interfaces::IGateway::Repay",
          members: [
            {
              name: "basic",
              type: "kapan::interfaces::IGateway::BasicInstruction",
            },
            {
              name: "context",
              type: "core::option::Option::<core::array::Span::<core::felt252>>",
            },
          ],
        },
        {
          type: "struct",
          name: "kapan::interfaces::IGateway::Withdraw",
          members: [
            {
              name: "basic",
              type: "kapan::interfaces::IGateway::BasicInstruction",
            },
            {
              name: "context",
              type: "core::option::Option::<core::array::Span::<core::felt252>>",
            },
          ],
        },
        {
          type: "enum",
          name: "kapan::interfaces::IGateway::LendingInstruction",
          variants: [
            {
              name: "Deposit",
              type: "kapan::interfaces::IGateway::Deposit",
            },
            {
              name: "Borrow",
              type: "kapan::interfaces::IGateway::Borrow",
            },
            {
              name: "Repay",
              type: "kapan::interfaces::IGateway::Repay",
            },
            {
              name: "Withdraw",
              type: "kapan::interfaces::IGateway::Withdraw",
            },
          ],
        },
        {
          type: "struct",
          name: "core::array::Span::<kapan::interfaces::IGateway::LendingInstruction>",
          members: [
            {
              name: "snapshot",
              type: "@core::array::Array::<kapan::interfaces::IGateway::LendingInstruction>",
            },
          ],
        },
        {
          type: "struct",
          name: "core::array::Span::<(core::starknet::contract_address::ContractAddress, core::felt252, core::array::Array::<core::felt252>)>",
          members: [
            {
              name: "snapshot",
              type: "@core::array::Array::<(core::starknet::contract_address::ContractAddress, core::felt252, core::array::Array::<core::felt252>)>",
            },
          ],
        },
        {
          type: "interface",
          name: "kapan::interfaces::IGateway::ILendingInstructionProcessor",
          items: [
            {
              type: "function",
              name: "process_instructions",
              inputs: [
                {
                  name: "instructions",
                  type: "core::array::Span::<kapan::interfaces::IGateway::LendingInstruction>",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_authorizations_for_instructions",
              inputs: [
                {
                  name: "instructions",
                  type: "core::array::Span::<kapan::interfaces::IGateway::LendingInstruction>",
                },
              ],
              outputs: [
                {
                  type: "core::array::Span::<(core::starknet::contract_address::ContractAddress, core::felt252, core::array::Array::<core::felt252>)>",
                },
              ],
              state_mutability: "external",
            },
          ],
        },
        {
          type: "impl",
          name: "INostraGatewayImpl",
          interface_name: "kapan::gateways::NostraGateway::INostraGateway",
        },
        {
          type: "struct",
          name: "core::array::Span::<core::starknet::contract_address::ContractAddress>",
          members: [
            {
              name: "snapshot",
              type: "@core::array::Array::<core::starknet::contract_address::ContractAddress>",
            },
          ],
        },
        {
          type: "struct",
          name: "kapan::interfaces::nostra::InterestRateConfig",
          members: [
            {
              name: "optimal_utilization_rate",
              type: "core::integer::u256",
            },
            {
              name: "base_borrowing_rate",
              type: "core::integer::u256",
            },
            {
              name: "rate_slope_1",
              type: "core::integer::u256",
            },
            {
              name: "rate_slope_2",
              type: "core::integer::u256",
            },
            {
              name: "general_protocol_fee",
              type: "core::integer::u256",
            },
            {
              name: "fees_recipient",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "interest_bearing_token",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "interest_bearing_collateral_token",
              type: "core::starknet::contract_address::ContractAddress",
            },
          ],
        },
        {
          type: "interface",
          name: "kapan::gateways::NostraGateway::INostraGateway",
          items: [
            {
              type: "function",
              name: "add_supported_asset",
              inputs: [
                {
                  name: "underlying",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "debt",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "collateral",
                  type: "core::starknet::contract_address::ContractAddress",
                },
                {
                  name: "ibcollateral",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_user_positions",
              inputs: [
                {
                  name: "user",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::array::Array::<(core::starknet::contract_address::ContractAddress, core::integer::u256, core::integer::u256)>",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_interest_rates",
              inputs: [
                {
                  name: "underlyings",
                  type: "core::array::Span::<core::starknet::contract_address::ContractAddress>",
                },
              ],
              outputs: [
                {
                  type: "core::array::Array::<kapan::interfaces::nostra::InterestRateConfig>",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "interest_rate_model",
              type: "core::starknet::contract_address::ContractAddress",
            },
          ],
        },
        {
          type: "event",
          name: "kapan::gateways::NostraGateway::NostraGateway::Event",
          kind: "enum",
          variants: [],
        },
      ],
      classHash:
        "0x2103eec8de057eadf6461be084f80b196f74f195e02b14366db6f859b424ca4",
    },
  },
} as const satisfies SNContractsType;

export default contracts;
