name: Test Contracts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          **/node_modules
          packages/hardhat/.yarn/cache
          packages/hardhat/.yarn/unplugged
          packages/hardhat/.yarn/install-state.gz
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-modules-

    - name: Cache Hardhat compilation
      uses: actions/cache@v3
      with:
        path: |
          packages/hardhat/cache
          packages/hardhat/artifacts
          packages/hardhat/typechain-types
        key: ${{ runner.os }}-hardhat-${{ hashFiles('packages/hardhat/contracts/**/*.sol') }}
        restore-keys: |
          ${{ runner.os }}-hardhat-

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      working-directory: packages/hardhat

    - name: Run unit tests
      run: yarn test
      working-directory: packages/hardhat
      env:
        ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}

    - name: Run fork tests
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: yarn test:fork
      working-directory: packages/hardhat
      env:
        ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
        MAINNET_FORKING_ENABLED: "true"
        COMPOUND_USDC_COMET: "0x9c4ec768c28520B50860ea7a15bd7213a9fF58bf"
        COMPOUND_WETH_COMET: "0x6f7D514bbD4aFf3BcD1140B7344b32f063dEe486"
        AAVE_POOL_ADDRESSES_PROVIDER: "0xa97684ead0e402dC232d5A977953DF7ECBaB3CDb"
        AAVE_UI_POOL_DATA_PROVIDER: "0x5c5228aC8BC1528482514aF3e27E692495148717"
        BALANCER_VAULT3: "0xbA1333333333a1BA1108E8412f11850A5C319bA9"
        BALANCER_VAULT2: "0xBA12222222228d8Ba445958a75a0704d566BF2C8" 